export const AppConst = {
  CHANGE_SCREEN: "CHANGE_SCREEN" as "CHANGE_SCREEN",
  TOGGLE_FULLSCREEN: "TOGGLE_FULLSCREEN" as "TOGGLE_FULLSCREEN",
  LAST_ACCESS: "LAST_ACCESS" as "LAST_ACCESS",
  LAUNCH: "LAUNCH" as "LAUNCH",
};

export const TodoConst = {
  ADD_TASK: "ADD_TASK" as "ADD_TASK",
};
